import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import TryYourselfEditor, { DEFAULT_EXAMPLE } from '../../components/TryYourselfEditor/TryYourselfEditor'
import AnalyticsView from '../../components/AnalyticsView/AnalyticsView'
import '../Page.css'
import '../TryYourself.css'

/**
 * NexAnalytics Interactive Demo
 *
 * Analytics dashboard with real WASM-powered metrics
 */
export default function TryNexAnalytics() {
  const [editorCode, setEditorCode] = useState(DEFAULT_EXAMPLE)

  return (
    <div className="page">
      <section className="page-hero-section">
        <div className="container">
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1rem' }}>
            <img
              src="/assets/icon_nexanalytics.svg"
              alt="NexAnalytics"
              style={{height: '60px', width: 'auto', maxWidth: '60px', objectFit: 'contain'}}
            />
            <h1>Try NexAnalytics</h1>
          </div>
          <p className="page-hero-description">
            Experience comprehensive model analytics with live quality metrics, coverage analysis, and complexity insights.
            Write SysML v2 code and see real-time analytics generated by WASM parsing.
          </p>
          <div style={{ marginTop: '1rem' }}>
            <Link to="/products/nexanalytics" className="btn ghost">
              ← Back to NexAnalytics Details
            </Link>
          </div>
        </div>
      </section>

      <section className="page-content-section">
        <div className="container">
          <div className="try-yourself-page-grid">
            <div className="editor-column">
              <TryYourselfEditor onCodeChange={setEditorCode} />
            </div>
            <div className="documentation-column">
              <AnalyticsView code={editorCode} />
            </div>
          </div>

          <div className="try-yourself-footer">
            <p className="try-yourself-note">
              <strong>NexAnalytics Features:</strong> WASM-powered quality metrics, documentation coverage tracking,
              complexity analysis, model statistics, and automated insights generation.
              For full analytics dashboards with team reporting and trend analysis, check out the{' '}
              <Link to="/platforms">VS Code Extension</Link>.
            </p>
          </div>
        </div>
      </section>
    </div>
  )
}
